name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test everything
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.4' # Define the elixir version [required]
        otp-version: '23.0' # Define the OTP version [required]

    - name: Setup node
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.8.0

    - name: Restore elixir dependencies cache
      uses: actions/cache@v2
      with:
        path: phoenix/deps phoenix/assets/node_modules angular/node_modules vue/node_modules react/node_modules
        key: ${{ runner.os }}-mix-${{ hashFiles('phoenix/mix.lock', 'phoenix/assets/package-lock.json', 'angular/package-lock.json', 'vue/package-lock.json', 'react/package-lock.json') }}
        restore-keys: ${{ runner.os }}-cache-

    - name: Install dependencies
      run: |
        (cd phoenix; mix deps.get)
        (cd phoenix/assets; npm i)
        (cd angular; npm i)
        (cd react; npm i)
        (cd vue; npm i)

    - name: Lint Phoenix
      run: npm run lint:phoenix

    - name: Lint Angular
      run: npm run lint:angular

    - name: Lint React
      run: npm run lint:react

    - name: Lint Vue
      run: npm run lint:vue

    - name: Run Elixir tests
      run: npm run test:ci:phoenix

    - name: Run Angular E2E tests
      run: npm run test:ci:angular

    - name: Run React E2E tests
      run: npm run test:ci:react

    - name: Run Vue E2E tests
      run: npm run test:ci:vue




