name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env: 
      working-directory: phoenix

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run elixir tests
      run: mix test
    - name: Start backend in E2E Env
      run: |
        MIX_ENV=e2e mix do ecto.reset
        MIX_ENV=e2e mix phx.server
    - name: Run Vue E2E tests
      run: |
        cd ../vue
        npm i
        npm run serve
        npm run test:e2e
    - name: Init react
      run: | 
        cd ../react
        npm i
        npm start
    - name: Run React E2E tests
      uses: DevExpress/testcafe-action@latest
      with:
        args: "firefox test/e2e/fixtures"
      
