name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test: 
    name: Build and test everything
    runs-on: ubuntu-16.04
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
            
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
        
    - name: Setup node
      uses: actions/setup-node@v2.1.1
      with: 
        node-version: 12.8.0   

    - name: Restore elixir dependencies cache
      uses: actions/cache@v2
      with:
        path: phoenix/deps angular/node_modules vue/node_modules react/node_modules
        key: ${{ runner.os }}-mix-${{ hashFiles('phoenix/mix.lock', 'angular/package-lock.json', 'vue/package-lock.json', 'react/package-lock.json') }}
        restore-keys: ${{ runner.os }}-cache-
        
    - name: Install elixir dependencies
      run: |
        cd phoenix
        mix deps.get
        
    - name: Run elixir tests
      run: |
        cd phoenix
        mix test
        
    - name: Build backend in E2E Env
      run: cd phoenix && MIX_ENV=e2e mix do ecto.reset  
    
    - name: Run Angular E2E tests
      run: |
        cd angular
        npm i
        npm run test:e2e:ci
        
    - name: Run React E2E tests
      run: |
        cd react
        npm i
        npm run test:e2e:ci

    - name: Run Vue E2E tests
      uses: cypress-io/github-action@v2
      with: 
        working-directory: vue
        project: vue
        start: npm run serve:e2e
        command: npm run test:e2e:ci  
        

      
